version: "3.3"
services:
  lms:
    build: .
    environment:
      FLASK_DEBUG: 0
      FLASK_APP: 'run.py'
    links:
      - db
    depends_on:
      - db
    ports:
      - "5000:5000"
    expose:
      - 5000
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: password
    volumes:
      - dbfolder/:/var/lib/postgresql

volumes:
  dbfolder:
    driver: local