"""add Tutor and Moderator

Revision ID: 12b0e8390634
Revises: b1c04abeab9e
Create Date: 2020-01-12 12:41:22.787337

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '12b0e8390634'
down_revision = 'b1c04abeab9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moderator',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('course_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['course_id'], ['course.url_id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.url_id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'course_id')
                    )
    op.create_table('tutor',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('course_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['course_id'], ['course.url_id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.url_id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'course_id')
                    )
    op.add_column('answer', sa.Column('homework_id', sa.Integer(), nullable=True))
    op.add_column('answer', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'answer', 'user', ['user_id'], ['url_id'])
    op.create_foreign_key(None, 'answer', 'homework', ['homework_id'], ['url_id'])
    op.add_column('student', sa.Column('entry_year', sa.Integer(), nullable=True))
    op.add_column('student', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('student_id_fkey', 'student', type_='foreignkey')
    op.create_foreign_key(None, 'student', 'user', ['user_id'], ['url_id'])
    op.drop_column('student', 'url_id')
    op.add_column('user', sa.Column('about_me', sa.String(), nullable=True))
    op.add_column('user', sa.Column('city', sa.String(), nullable=True))
    op.add_column('user', sa.Column('facebook_link', sa.String(), nullable=True))
    op.add_column('user', sa.Column('instagram_link', sa.String(), nullable=True))
    op.add_column('user', sa.Column('is_moderator', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_tutor', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('linkedin_link', sa.String(), nullable=True))
    op.add_column('user', sa.Column('middle_name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('password_hash', sa.String(), nullable=True))
    op.add_column('user', sa.Column('vk_link', sa.String(), nullable=True))
    op.drop_column('user', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'vk_link')
    op.drop_column('user', 'password_hash')
    op.drop_column('user', 'middle_name')
    op.drop_column('user', 'linkedin_link')
    op.drop_column('user', 'is_tutor')
    op.drop_column('user', 'is_moderator')
    op.drop_column('user', 'instagram_link')
    op.drop_column('user', 'facebook_link')
    op.drop_column('user', 'city')
    op.drop_column('user', 'about_me')
    op.add_column('student', sa.Column('url_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.create_foreign_key('student_id_fkey', 'student', 'user', ['url_id'], ['url_id'])
    op.drop_column('student', 'user_id')
    op.drop_column('student', 'entry_year')
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.drop_column('answer', 'user_id')
    op.drop_column('answer', 'homework_id')
    op.drop_table('tutor')
    op.drop_table('moderator')
    # ### end Alembic commands ###
