"""initial db creation

Revision ID: b1c04abeab9e
Revises: 
Create Date: 2020-01-11 18:46:15.001163

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b1c04abeab9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('answer', sa.String(), nullable=True),
                    sa.Column('submit_date', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('course',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('group',
                    sa.Column('num', sa.Integer(), nullable=False),
                    sa.Column('degree', sa.String(), nullable=True),
                    sa.Column('grade', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('num')
                    )
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('family_name', sa.String(), nullable=True),
                    sa.Column('status', sa.String(), nullable=True),
                    sa.Column('verification_code', sa.String(), nullable=True),
                    sa.Column('email', sa.String(), nullable=True),
                    sa.Column('phone', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('homework',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('valid_from', sa.DateTime(), nullable=True),
                    sa.Column('valid_to', sa.DateTime(), nullable=True),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('course_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('material',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('text', sa.String(), nullable=True),
                    sa.Column('date', sa.DateTime(), nullable=True),
                    sa.Column('course_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('student',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('group_num', sa.Integer(), nullable=True),
                    sa.Column('pay_flg', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['group_num'], ['group.num'], ),
                    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('material')
    op.drop_table('homework')
    op.drop_table('user')
    op.drop_table('group')
    op.drop_table('course')
    op.drop_table('answer')
    # ### end Alembic commands ###
