"""User middle name update

Revision ID: c4539a05366e
Revises: ded18963434d
Create Date: 2020-01-15 18:23:02.812725

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c4539a05366e'
down_revision = 'ded18963434d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculum',
                    sa.Column('course_id', sa.Integer(), nullable=False),
                    sa.Column('group_num', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['course_id'], ['course.url_id'], ),
                    sa.ForeignKeyConstraint(['group_num'], ['group.num'], ),
                    sa.PrimaryKeyConstraint('course_id', 'group_num')
                    )
    op.alter_column('student', 'entry_year',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('user', 'middle_name',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'middle_name',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('student', 'entry_year',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.drop_table('curriculum')
    # ### end Alembic commands ###
