apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms
  labels:
    name: lms
spec:
  replicas: 4
  selector:
    matchLabels:
      name: lms
  template:
    metadata:
      name: lms
      labels:
        name: lms
    spec:
      containers:
        - name: lms
          image: lms:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 512Mi